import type { Muscle } from '@/lib/muscles';

export const SEED_EXERCISES: { name: string; muscles: Muscle[] }[] = [
  { name: 'Bench Press', muscles: ['chest', 'triceps', 'shoulders'] },
  { name: 'Incline DB Press', muscles: ['chest', 'shoulders', 'triceps'] },
  { name: 'Push-Up', muscles: ['chest', 'triceps', 'shoulders'] },
  { name: 'Overhead Press', muscles: ['shoulders', 'triceps'] },
  { name: 'Lateral Raise', muscles: ['shoulders'] },
  { name: 'Pull-Up', muscles: ['back', 'biceps'] },
  { name: 'Lat Pulldown', muscles: ['back', 'biceps'] },
  { name: 'Barbell Row', muscles: ['back', 'biceps'] },
  { name: 'Seated Cable Row', muscles: ['back', 'biceps'] },
  { name: 'Deadlift', muscles: ['back', 'hamstrings', 'glutes'] },
  { name: 'Romanian Deadlift', muscles: ['hamstrings', 'glutes', 'back'] },
  { name: 'Squat', muscles: ['quads', 'glutes'] },
  { name: 'Front Squat', muscles: ['quads', 'glutes', 'core'] },
  { name: 'Leg Press', muscles: ['quads', 'glutes'] },
  { name: 'Lunge', muscles: ['quads', 'glutes'] },
  { name: 'Leg Extension', muscles: ['quads'] },
  { name: 'Leg Curl', muscles: ['hamstrings'] },
  { name: 'Hip Thrust', muscles: ['glutes', 'hamstrings'] },
  { name: 'Calf Raise', muscles: ['calves'] },
  { name: 'Barbell Curl', muscles: ['biceps'] },
  { name: 'Hammer Curl', muscles: ['biceps', 'forearms'] },
  { name: 'Tricep Pushdown', muscles: ['triceps'] },
  { name: 'Skull Crusher', muscles: ['triceps'] },
  { name: 'Dip', muscles: ['triceps', 'chest', 'shoulders'] },
  { name: 'Face Pull', muscles: ['shoulders', 'back'] },
  { name: 'Plank', muscles: ['core'] },
  { name: 'Hanging Leg Raise', muscles: ['core'] },
  { name: 'Cable Crunch', muscles: ['core'] },
  { name: 'Wrist Curl', muscles: ['forearms'] },
  { name: 'Shrug', muscles: ['back'] },
];
